/*console-ის გამოყენებით ჩანს შედეგები საიტზე, inspect-ში. .log() იგივეა რაც print() პითონში. */
console.log(true)
console.log(typeof 1)
console.log(typeof "hi")
console.log(NaN)
console.log(null)
console.log(1 + 1)
console.log(2 + "2")
console.log(1-1)
console.log("2"-"2")
console.log(1*2)
console.log(5*5)
console.log(6/5)
console.log(4/5)
console.log(2 % 1)
console.log(26 % 7)